services:
  serving:
    build:
      context: .
      target: develop
    command: /models/start_triton_server.sh
    ports:
      - 8504:8500
      - 8505:8501
    volumes:
      - ./models:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: 2GB

  develop:
    build:
     context: .
     target: util
     args:
      - UID=${UID}
      - GID=${GID}
    user: "devuser"
    command: ["sleep", "infinity"]
    working_dir: /workspace/dlomix-serving
    volumes:
     - .:/workspace/dlomix-serving:Z

  reverse-proxy:
    image: nginx
    depends_on:
      - serving
    ports:
      - 8502:8502
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']

  swagger_gen:
    image: python
    depends_on: 
      - reverse-proxy
      - serving
    environment:
      TRITON_SERVER_IP: "10.152.171.77"
      TRITON_REVERSE_PROXY_SERVER_PORT: "8502"
    volumes:
      - ./:/workspace
    command:
      - /bin/sh
      - -c 
      - |
        pip install requests
        pip install jinja2
        pip install PyYAML
        cd /workspace/swagger
        python swagger_gen.py

  swagger:
    image: swaggerapi/swagger-ui
    depends_on:
      swagger_gen:
        condition: service_completed_successfully
    ports:
      - 8080:8080
    environment:
      SWAGGER_JSON: /workspace/swagger/swagger_test.yml
    volumes:
      - ./:/workspace