services:
  serving:
    build:
      context: .
      target: develop
    command: /models/start_triton_server.sh
    volumes:
      - ./models:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: 2GB
    restart: unless-stopped

  develop:
    build:
     context: .
     target: util
     args:
      UID: ${UID_}
      GID: ${GID}
    user: "devuser"
    command: ["sleep", "infinity"]
    working_dir: /workspace/dlomix-serving
    volumes:
     - .:/workspace/dlomix-serving:Z
    depends_on:
      serving:
        condition: service_healthy
