openapi: 3.0.3
info:
  title: Swagger Triton Prosit model serving - OpenAPI 3.0
  description: |-
    This is a documentation file for Prosit Triton models
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://10.152.171.77:8502/v2/models
tags:
  - name: model
    description: Everything about Prosit model
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:

  /Prosit_2019_intensity_ensemble/infer:
     post:
      tags:
        - model
      summary: Get prediction
      description: Get prediction
      operationId: infer
      requestBody:
        description: Get a prediction
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Prosit_2019_intensity_ensemble_input'
          application/xml:
            schema:
              $ref: '#/components/schemas/Prosit_2019_intensity_ensemble_input'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Prosit_2019_intensity_ensemble_input'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Prosit_2019_intensity_ensemble_output'
            application/xml:
              schema:
                $ref: '#/components/schemas/Prosit_2019_intensity_ensemble_output'
        '405':
          description: Invalid input


components:
  schemas:
    parameters:
      type: object
      properties:
        sequence_id:
          type: integer
          example: 0
        sequence_start:
          type: boolean
          example: false
        sequence_end:
          type: boolean
          example: false


  
    Prosit_2019_intensity_ensemble_output:
      type: object
      properties:
        id:
          type: string
          example: "it_can_be_anything"
        model_name:
          type: string
          example: "Prosit_2019_intensity_ensemble"
        model_version:
          type: string
          example: "1"
        parameters:
          $ref: '#/components/schemas/parameters'
        outputs:
          type: array
          items:
            allOf:
            
              - $ref: '#/components/schemas/Prosit_2019_intensity_ensemble_output_out/Reshape:1'
            
              - $ref: '#/components/schemas/Prosit_2019_intensity_ensemble_output_out/Reshape:2'
            

  
    Prosit_2019_intensity_ensemble_output_out/Reshape:1:
        type: object
        properties:
          name:
            type: string
            example: "out/Reshape:1"
          datatype:
            type: string
            example: "FP32"
          shape:
            type: array
            items:
              type: number
              example: [1,174]
          data:
            type: array
            items:
              type: number
              example: [0.461770623922348, -1.0, -1.0, 0.06809068471193314, -1.0, -1.0, 0.32882586121559143, -1.0, -1.0, 0.13633368909358978, -1.0, -1.0, 0.6066970825195312, -1.0, -1.0, 0.47628480195999146, -1.0, -1.0, 0.8252231478691101, -1.0, -1.0, 0.6286046504974365, -1.0, -1.0, 0.8001991510391235, -1.0, -1.0, 0.6677533388137817, -1.0, -1.0, 0.6667646765708923, -1.0, -1.0, 1.0, -1.0, -1.0, 0.24044056236743927, -1.0, -1.0, 0.8719386458396912, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]

  
    Prosit_2019_intensity_ensemble_output_out/Reshape:2:
        type: object
        properties:
          name:
            type: string
            example: "out/Reshape:2"
          datatype:
            type: string
            example: "FP32"
          shape:
            type: array
            items:
              type: number
              example: [1,174]
          data:
            type: array
            items:
              type: number
              example: [0.461770623922348, -1.0, -1.0, 0.06809068471193314, -1.0, -1.0, 0.32882586121559143, -1.0, -1.0, 0.13633368909358978, -1.0, -1.0, 0.6066970825195312, -1.0, -1.0, 0.47628480195999146, -1.0, -1.0, 0.8252231478691101, -1.0, -1.0, 0.6286046504974365, -1.0, -1.0, 0.8001991510391235, -1.0, -1.0, 0.6677533388137817, -1.0, -1.0, 0.6667646765708923, -1.0, -1.0, 1.0, -1.0, -1.0, 0.24044056236743927, -1.0, -1.0, 0.8719386458396912, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]

  

    Prosit_2019_intensity_ensemble_input:
      type: object
      properties:
        id:
          type: string
          example: "it_can_be_anything"
        inputs:
          type: array
          example: [{'name': 'precursor_charge_in_int:0', 'shape': [1, 1], 'datatype': 'INT32', 'data': [1]}, {'name': 'collision_energy_in:0', 'shape': [1, 1], 'datatype': 'FP32', 'data': [0.25]}, {'name': 'peptides_in_str:0', 'shape': [1, 1], 'datatype': 'BYTES', 'data': ['AAAAAKAK']}]
          items:
            allOf:
              
              - $ref: "#/components/schemas/Prosit_2019_intensity_ensemble_input_peptides_in_str:0"
              
              - $ref: "#/components/schemas/Prosit_2019_intensity_ensemble_input_precursor_charge_in_int:0"
              
              - $ref: "#/components/schemas/Prosit_2019_intensity_ensemble_input_collision_energy_in:0"
              
        
  
    Prosit_2019_intensity_ensemble_input_peptides_in_str:0:
      type: object
      properties:
        name:
          type: string
        shape:
          type: array
          items:
            type: integer
        datatype:
          type: string
        data:
          type: array
          items:
            type: string
  
    Prosit_2019_intensity_ensemble_input_precursor_charge_in_int:0:
      type: object
      properties:
        name:
          type: string
        shape:
          type: array
          items:
            type: integer
        datatype:
          type: string
        data:
          type: array
          items:
            type: string
  
    Prosit_2019_intensity_ensemble_input_collision_energy_in:0:
      type: object
      properties:
        name:
          type: string
        shape:
          type: array
          items:
            type: integer
        datatype:
          type: string
        data:
          type: array
          items:
            type: string
  
