name: Run tests, styling and linting

on:
  pull_request:
    branches:
      - feature/generic_fragment_mz_model

jobs:

  test_style_lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Download models 
        run: ./getModels.sh

      - name: Build the docker-compose stack
        run: docker-compose up -d

      - name: Run pytest
        run: docker exec develop pytest
